name: maa_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1
  - flask=2.0.1
  - pandas=1.3.3
  - numpy=1.21.2
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - psutil=5.8.0
  - werkzeug=2.0.1
  - gunicorn=20.1.0
  - gevent=21.8.0
  - pip:
    - accelerate
    - pyyaml
    - requests
    - tqdm
    - scikit-learn
    - tensorboard
    - wandb
  - pip:
    - packaging
    - regex
    - opencv-python
    - tabulate
    - termcolor
    - beautifulsoup4
    - six
    - joblib
    - lazy-loader
    - msgpack
    - numba
    - scipy
    - yapf
    - imageio<3.0
    - absl-py
    - markdown
    - protobuf
    - pyasn1-modules
    - urllib3
    - appdirs
    - wcwidth
    - cffi 